name: Dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
     - name: apt install dependency
      run: 
         sudo apt-get -y install valgrind
         
    - name: Dynamic Analysis
       run: make dynamic_analysis -c 3_Implementation
 
    
